language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm run build:prod

install:
  - npm install -g travis-ci-cloudfront-invalidation
  - npm install

deploy:
  on:
    branch: master
  provider: s3
  access_key_id: $AWS_ACCESS_ID
  secret_access_key: $AWS_ACCESS_KEY
  bucket: $BUCKET
  skip_cleanup: true
  local_dir: build
  acl: public_read

after_deploy:
  - travis-ci-cloudfront-invalidation -a $AWS_ACCESS_ID -s $AWS_ACCESS_KEY -c $AWS_CLOUDFRONT_DIST_ID -i '/*' -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST
